using System.Diagnostics.CodeAnalysis;

namespace ProSoft.DnsBL.Api.Models;

public sealed class BlockList : IDisposable
{
	public Guid SystemId { get; set; }

	public int Id { get; set; }

	public string Title { get; set; }

	public string Url { get; set; }

	public BlocklistType BlocklistType { get; set; }

	#region IDisposable Interface Implementation

	private bool _disposed;

	/// <summary>
	/// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
	/// </summary>
	/// <autogeneratedoc />
	[ExcludeFromCodeCoverage]
	public void Dispose()
	{
		this.Dispose(true);
		GC.SuppressFinalize(this);
	}

	/// <summary>
	/// Releases unmanaged and - optionally - managed resources.
	/// </summary>
	/// <param name="disposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
	/// <autogeneratedoc />
	[ExcludeFromCodeCoverage]
	private void Dispose(bool disposing)
	{
		if (!_disposed && disposing)
		{
			// Disposing Logic
		}

		_disposed = true;
	}

	/// <summary>
	/// Finalizes an instance of the <see cref="BlockList"/> class.
	/// </summary>
	/// <autogeneratedoc />
	[ExcludeFromCodeCoverage]
	~BlockList()
	{
		this.Dispose(false);
	}

	#endregion
}
